# env:
#   global:
#     - CC_TEST_REPORTER_ID=ce1177050144a136200e2f02e12b80c4e889eb6165703d84e12a1d1b29d4f423
language: node_js
sudo: false
node_js:
  - "7.1.0"
install:
  - npm install
script:
  - gulp build
# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: npm run deploy
notifications: # set notification options
  email:
    recipients:
      - thedaviddias@gmail.com
branches:
  only:
    - master
    - /^greenkeeper/.*$/
# deploy:
#   local_dir: dist
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master
env:
  global:
    - QIITA_POST_ID: 8fff46c201bf9eaeba4a
    - QIITA_POST_TITLE: "フロントエンドチェックリスト（日本語訳）"
    - secure: BT8j/bT0mWtdp9GE0y8ey9DsChCX14iL5Lw3/O7SCtyJdcAF2kXCANUV9Uav/KD7VMa57RfKKpzoOm/l1Zbzt3Q2dniFHGICCSTDcnsBuXBKjvpVKimP+kIxtCmH7qN58er4PV09PZFupQy7X0dd6FvKK09kBwfBCBw1fUfmTtCUfh541024mVw+0uaqTst/7b/OlsI3jnNrVo6ixjN5jVpaHwpP3pLm1OQNaK92NmBFdmtIxq1i/sNuoSyvHs30GrCaqHF/2d95EZiN7+EKO+6yxaLbRNVXOhqO2ksK0yeXS/auXhw3eJ3VqcUQivs6UA+s6+GzUbKvR9VLokfPV5hm5yNcpuoCnRaMy0vnJ44hA68QQ/Yt8NXHMD8PS0S9FEnuX++yBYMM55bVB63iwGiPvFIpzaOGu5/DlceQGA3chw2v+Z9G3bPAM/XC3cJIzwbY5KOpqdXigbaNvbWCW+EElsqSCEGZFo5+VfTllUZ+gGc52crKk7HFJ/XBw6Rmuaub8U2PiqnddopjWUJA9MWnAE9i8LPnBa4ZJqyBTDdhl+QbtnvMD4BNnScuwKp8j85g+Wu3A7jNHQQ5Qld+rCoDnHe3H6VczY5lwuan8Em0LwI9eeOP5S8RA0b5nK4I3/Fmq3RAm+vdF/vRphzjauXUi/B+0irpbTnjSfEPWpU=
